---
title: "project_visualizations"
output: html_document
date: '2022-05-18'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#libraries
```{r}
library(tidyverse)
library(ggpubr)
library(patchwork)
source("func_file.R")
```

#dataload
```{r, include = FALSE}
ragweed <- read_tsv("../../data/normalized_donor_data_ragweed.tab", col_names = FALSE)

ragweed_flat <- read_tsv("../../data/core_similarity_data_flat_ragweed.tab", col_names = TRUE)
```

# donor HLA data overview
```{r}
ragweed_HLA_data <- read_tsv("../../data/ragweed_donor_HLA_flat.txt", col_names = FALSE)

ragweed_HLA_plot <- ragweed_HLA_data %>% 
  group_by(X2) %>% 
  count() %>% 
  ggplot(mapping = aes(x = n,
                       y = X2)) +
  geom_col() +
  geom_text(aes(label = n), 
            hjust = -0.5) +
  xlim(0,11) +
  theme_minimal() +
  labs(title = "HLA coverage ragweed") +
  theme(plot.title = element_text(size = 20),
        axis.text.y = element_text(size=12),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(), 
        axis.title.x = element_blank(),
        axis.title.y = element_blank())

# Save plot to results.

ggsave(filename = "../../results/report/ragweed_HLA_plot.png", 
       plot = ragweed_HLA_plot,
       width = 6,
       height = 10)
```

#renaming ragweed col names
```{r}
ragweed <- ragweed %>% 
  rename(donor = X1, 
         peptide = X2, 
         si = X3, 
         best_7_allele_rank = X4, 
         best_donor_rank = X5, 
         normalized_7_allele = X6, 
         normalized_donor = X7) %>% 
  mutate(sig_si = case_when(si >= 3.5 ~ 1 / (1 + exp(-(si-3.5)*0.5)), 
                            si < 3.5 ~ 1 / (1 + exp(-(si-3.5)*2)))) %>% 
  mutate(Reactivity = case_when(si >= 3 ~ "Reactive", 
                                si < 3 ~ "Non Reactive"))

```

#Scatterplots 7 allele
```{r}
#scatterplot si vs. 7 allele rank
scatter_7_allele <- ragweed %>% 
  scatter_plot(best_7_allele_rank, si, si_filter = FALSE, "SI as a function of 7 allele rank", "7 allele rank", "SI")

#scatterplot si. 7 allele rank normalized
scatter_7_allele_norm <- ragweed %>% 
  scatter_plot(normalized_7_allele, si, si_filter = FALSE, "SI as a function of normalized 7 allele rank", "Normalized 7 allele rank", "SI")

```

#scatterplot donor rank 
```{r}
#scatterplot si vs. donor rank 
scatter_donor <- ragweed %>% 
  scatter_plot(best_donor_rank, si, si_filter = FALSE, "SI as a function of donor rank", "Donor rank", "")

#scatter_norm_sig <- ragweed %>% 
 # scatter_plot(normalized_donor, sig_si, si_filter = FALSE, "", "Normalized donor  rank", "Sigmoid SI")

#scatterplot si. vs. donor rank normalized
scatter_donor_norm <- ragweed %>% 
  scatter_plot(normalized_donor, si, si_filter = FALSE, "SI as a function of normalized donor rank", "Normalized donor rank", "")
```

#saving combined scatterplots w. patchwork: 
```{r}
ggsave(filename = "../../results/report/si_vs_rank_ragweed.png",
       plot = (scatter_7_allele + scatter_donor),
       width = 9,
       height = 4.5)

ggsave(filename = "../../results/report/si_vs_rank_norm_ragweed.png", 
       plot = (scatter_7_allele_norm + scatter_donor_norm),
       width = 9, 
       height = 4.5)
```

#boxplots
```{r}


boxplot_7_allele <- ragweed %>% 
  boxplot(Reactivity, best_7_allele_rank, "", "Reactivity", "Normalized 7 allele rank")

boxplot_donor <- ragweed %>% 
  boxplot(Reactivity, best_donor_rank, "", "Reactivity", "Normalized 7 allele rank")

ggsave(filename = "../../results/report/boxplots_std_ragweed.png", 
       plot = (boxplot_7_allele + boxplot_donor),
       width = 9, 
       height = 4.5)

#plots for normalized ranks ----------

boxplot_7_allele_norm <- ragweed %>% 
  boxplot(Reactivity, normalized_7_allele, "", "Reactivity", "Normalized 7 allele rank")

boxplot_donor_norm <- ragweed %>% 
  boxplot(Reactivity, normalized_donor, "", "Reactivity", "Normalized Donor Rank" )

ggsave(filename = "../../results/report/boxplots_norm.png", 
       plot = (boxplot_7_allele_norm + boxplot_donor_norm),
       width = 9, 
       height = 4.5)

```


#scatterplot: SI(H) vs. SI(L)
```{r}
scatter_si_vs_si <- ragweed_flat %>% 
  scatter_plot(SI_h, SI_l, si_filter = FALSE, "", "SI low", "SI high")

scatter_si_vs_si

ragweed_flat_aug <- ragweed_flat %>% 
  mutate(Group = case_when(SI_l <= 0.5 & SI_h >= 0.5 ~ "Non cross reactive", 
                           SI_l > 0.5 & SI_h > 0.5 ~ "Cross reactive", 
                           SI_l < 0.5 & SI_h < 0.5 ~ "Non reactive"))

si_vs_si <- ggplot(ragweed_flat_aug, mapping = aes(x = SI_h, 
                                                   y = SI_l, 
                                                   color = Group)) +
    
      geom_point(size = 1, alpha = 0.5) + 
      labs(title = "SI low as a function of SI high", 
           x = "SI High", 
           y = "SI low") +
      theme(plot.title = element_text(size=15))
    
ggsave(filename = "../../results/report/si_vs_si_ragweed.png", 
       plot = si_vs_si,
       width = 9, 
       height = 4.5)



```

```{r}
ragweed_flat_aug %>% 
  filter(Group != "Group 3") %>% 
  boxplot(Group, bvc_core_bl, "", "", "Core similarity")
```








