---
title: "project_visualization_tree"
output: html_document
date: '2022-05-18'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#libraries
```{r}
library(tidyverse)
library(ggpubr)
library(patchwork)
source("func_file.R")
```

#dataload
```{r}
tree <- read_tsv("../../data/normalized_donor_data_tree.tab", col_names = FALSE)

tree_flat <- read_tsv("../../data/core_similarity_data_flat_tree.tab", col_names = TRUE)
```

# donor HLA data overview
```{r}
tree_HLA_data <- read_tsv("../../data/tree_donor_HLA_flat.txt", col_names = FALSE)

tree_HLA_plot <- tree_HLA_data %>% 
  group_by(X2) %>% 
  count() %>% 
  ggplot(mapping = aes(x = n,
                       y = X2)) +
  geom_col() +
  geom_text(aes(label = n), 
            hjust = -0.5) +
  xlim(0,9) +
  theme_minimal() +
  labs(title = "HLA coverage tree") +
  theme(plot.title = element_text(size = 20),
        axis.text.y = element_text(size=12),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(), 
        axis.title.x = element_blank(),
        axis.title.y = element_blank())

# Save plot to results.

ggsave(filename = "../../results/report/tree_HLA_plot.png", 
       plot = tree_HLA_plot,
       width = 6,
       height = 4.1)
```

#renaming col names
```{r}
tree <- tree %>% 
  rename(donor = X1, 
         peptide = X2, 
         si = X3, 
         best_7_allele_rank = X4, 
         best_donor_rank = X5, 
         normalized_7_allele = X6, 
         normalized_donor = X7) %>% 
  mutate(sig_si = case_when(si >= 3.5 ~ 1 / (1 + exp(-(si-3.5)*0.5)), 
                            si < 3.5 ~ 1 / (1 + exp(-(si-3.5)*0.2)))) %>% 
  mutate(Reactivity = case_when(si >= 3 ~ "Reactive", 
                                si < 3 ~ "Non Reactive"))
```



#boxplots for normalized ranks:
```{r}
boxplot_7_allele_norm <- tree %>% 
  boxplot(Reactivity, normalized_7_allele, "", "Reactivity", "Normalized 7 allele rank")

boxplot_donor_norm <- tree %>% 
  boxplot(Reactivity, normalized_donor, "", "Reactivity", "Normalized Donor Rank" )

ggsave(filename = "../../results/report/boxplots_norm_tree.png", 
       plot = (boxplot_7_allele_norm + boxplot_donor_norm),
       width = 9, 
       height = 4.5)
```

```{r}
tree_flat_aug <- tree_flat %>% 
  mutate(Group = case_when(SI_l <= 0.5 & SI_h >= 0.5 ~ "Non cross reactive", 
                           SI_l > 0.5 & SI_h > 0.5 ~ "Cross reactive", 
                           SI_l < 0.5 & SI_h < 0.5 ~ "Non reactive"))

boxplot_bvc_core_sim <- tree_flat_aug %>% 
  filter(Group != "Non reactive") %>% 
  boxplot_core_sim(Group, bvc_core_bl, "", "", "Core similarity")

boxplot_bvb_core_sim <- tree_flat_aug %>%  
  filter(Group != "Non reactive") %>% 
  boxplot_core_sim(Group, bvb_core_bl, "", "", "Core similarity")

boxplot_rand_core_sim <-tree_flat_aug %>%  
  filter(Group != "Non reactive") %>% 
  boxplot_core_sim(Group, rand_core_bl, "", "", "Rand core similarity")

ggsave(filename = "../../results/report/boxplot_bvc_core_sim_tree.png", 
       plot = boxplot_bvc_core_sim,
       width = 9, 
       height = 8)

ggsave(filename = "../../results/report/boxplot_bvb_core_sim_tree.png", 
       plot = boxplot_bvb_core_sim,
       width = 9, 
       height = 8)

ggsave(filename = "../../results/report/boxplot_rand_core_sim_tree.png", 
       plot = boxplot_rand_core_sim,
       width = 9, 
       height = 8)
```



